image: gitpod/workspace-node-lts

ports:
  - port: 5173
    onOpen: open-preview
    visibility: public

tasks:
  - name: Install Dependencies
    init: npm install
  - name: Start Dev Server
    command: npm run dev

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode

